default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: MFISNotarialDB
  username: root
  password: secret
  host: localhost

test:
  <<: *default
  database: MFISNotarialDB_test
  username: root
  password: secret
  host: localhost

production:
  <<: *default
  database: MFISNotarialDB
  username: root
  password: secret
  host: localhost
